#!/usr/bin/env python
import rospy
from sensor_msgs.msg import PointCloud2
import numpy as np
import rospkg
import sys

rospy.init_node('pc_sender')
rospack = rospkg.RosPack()
msg = PointCloud2()
path = rospack.get_path('demo')+'/pc/pc.txt'
with open(path, 'r') as infile:
    msg.deserialize(infile.read())
msg.header.frame_id = 'static_camera_link'
pub = rospy.Publisher("/static_points2",PointCloud2, queue_size =1, latch = True)
pub.publish(msg)
rospy.spin()



