#!/usr/bin/env python
import rospy
import signal
import sys
import math
import tf
import PyKDL
import copy

from std_msgs.msg import String
from nav_msgs.msg import Path
from sensor_msgs.msg import JointState

import numpy as np 

REFERENCE_FRAME='panda_link0'

class Simulator(object):
    def __init__(self):
        self._tl = tf.TransformListener()
        self._br = tf.TransformBroadcaster()
        rospy.sleep(1.) # sleep a bit to make sure the TF cache is filled

        #Rviz value
        self._viz_pub = rospy.Publisher("/viz/joint_states", JointState, queue_size = 5)

        #Simulator State
        self._finger_val = .035
        self._current_joint = [0.0,-0.4,0.0,-2.0,0.0,1.6,0.8,self._finger_val,self._finger_val]
        self._current_velocity = [0.,0.,0.,0.,0.,0.,0.,0.,0.]
        self._freq = 200
        self._vel_sub = rospy.Subscriber("/jacob/joint_vel", JointState, self.on_vel)
        self._action_sub = rospy.Subscriber("/subaction", String, self.on_command, queue_size = 1)
        self._state_sub = rospy.Subscriber("/viz/joint_states", JointState, self.update_position, queue_size = 1)
        #Publish init state for the robot
        self.init_states()
        self._init = False
        self._sim = True

    def init_states(self):
        joint = JointState()
        joint.header.stamp = rospy.Time.now()
        joint.name = ["panda_joint1", "panda_joint2","panda_joint3","panda_joint4","panda_joint5","panda_joint6","panda_joint7","panda_finger_joint1","panda_finger_joint2"]
        joint.position = self._current_joint
        self._viz_pub.publish(joint)

    def on_vel(self,msg):
        for i,v in enumerate(msg.velocity):
            self._current_velocity[i]=v

    def run(self):
        r = rospy.Rate(self._freq)
        while not rospy.is_shutdown():
            self.move()
            r.sleep()

    def move(self):
        for i,v in enumerate(self._current_velocity):
            self._current_joint[i]+=v/self._freq
        joint = JointState()
        joint.header.stamp = rospy.Time.now()
        joint.name = ["panda_joint1", "panda_joint2","panda_joint3","panda_joint4","panda_joint5","panda_joint6","panda_joint7","panda_finger_joint1","panda_finger_joint2"]
        joint.position = list(self._current_joint)
        self._viz_pub.publish(joint)
        
    def update_position(self,msg):
        global joint_position
        joint_position = list(msg.position)

    def on_command(self, msg):
        global joint_position
        if self._sim:
            if msg.data == "grasp":
                self._finger_val = 0.0
                self._current_joint = joint_position
                self._current_joint[-1] = self._finger_val
                self._current_joint[-2] = self._finger_val
            if msg.data == "release":
                self._finger_val = .035
                self._current_joint = joint_position
                self._current_joint[-1] = self._finger_val
                self._current_joint[-2] = self._finger_val
        
    def signal_handler(self, signal, frame):
        sys.exit(0)

if __name__ == "__main__":
    rospy.init_node("simulator")
    simulator = Simulator()
    signal.signal(signal.SIGINT, simulator.signal_handler)
    simulator.run()

